### ISSUE TITLE
An item with the same key has already been added. Key: 24

### ISSUE THREAD

**Issue by Aholicknight** [Washi1337/OldRod#66]
I am getting `An item with the same key has already been added. Key: 24` when I am trying to unpack a koi protected exe. I downloaded the repo, built the project as a release (I did not change anything) and getting this error. Here is the full log:

```
08:57:43.676 [TUI]: Something went wrong! Try the latest version or report a bug at the repository.
08:57:43.718 [TUI]: System.ArgumentException: An item with the same key has already been added. Key: 24
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OldRod.Pipeline.Stages.ConstantsResolution.ConstantsResolutionStage.AutoDetectConstants(DevirtualisationContext context) in C:\Users\Aholicknight\Source\Repos\OldRod\src\OldRod.Pipeline\Stages\ConstantsResolution\ConstantsResolutionStage.cs:line 92
   at OldRod.Pipeline.Stages.ConstantsResolution.ConstantsResolutionStage.Run(DevirtualisationContext context) in C:\Users\Aholicknight\Source\Repos\OldRod\src\OldRod.Pipeline\Stages\ConstantsResolution\ConstantsResolutionStage.cs:line 43
   at OldRod.Pipeline.Devirtualiser.RunPipeline(DevirtualisationContext context) in C:\Users\Aholicknight\Source\Repos\OldRod\src\OldRod.Pipeline\Devirtualiser.cs:line 213
   at OldRod.Pipeline.Devirtualiser.Devirtualise(DevirtualisationOptions options) in C:\Users\Aholicknight\Source\Repos\OldRod\src\OldRod.Pipeline\Devirtualiser.cs:line 92
   at OldRod.Program.Main(String[] args) in C:\Users\Aholicknight\Source\Repos\OldRod\src\OldRod\Program.cs:line 207
```

Any help would be appreciated. Thanks!

**Comment by Washi1337** [comment]
This would be hard to pinpoint without any way for me to reproduce the error, but this is very likely because of some modification to vanilla KoiVM.

Please provide all the information, as was indicated by the bug report issue template.
